### ISSUE TITLE
Not winning, tying instead

### ISSUE THREAD

**Issue by cmahaffey** [cmahaffey/TicTacToe#1]
## UserStory
- to be able to play on a tictactoe board of any size and win, lose or draw
## testStatement
- when a game board is created, the game should be able to determine if the game is at a win, lose, or draw situation
## Context and Description
- Runs fine when tested for horizontal, vertical, and diagonal when run alone, but breaks (sometimes) when an x is added. May break on x too, but haven't found any issues in brief tests
- I assume it's a problem with the if statements, as it seems that it won't go into the final if statement when I console log. making two seperate if statements did not work, however.
- have tested on various boxes. As my final upload was a working test, a broken box is provided below.

box=[[[' '],[' '],[' ']],[[' '],['x'],[' ']],[['o'],['o'],['o']]];
## Winerror message

No error, just doesn't perform as functioned

**Comment by amadden80** [comment]
Could we simplify this first by removing the large conditional based on player?
I'd suggest moving it to an object.  

Also:  This is too much code in one place.  We could spend time reasoning with it, but it's better use of time to break this into smaller parts.

Regarding the issue, could you try console logging the i and j values?  As I run it through my head, I don't get the indexes I'm expecting given you logic.
