### ISSUE TITLE
Inserting names for two players

### ISSUE THREAD

**Issue by cmahaffey** [cmahaffey/TicTacToe#2]
## user story

As a user I want to be able to insert my name as either player 1, or player 2.
## test statement
- prompt a user for an input and replace player 1's name
- prompt a user for another input and replace player 2's name
## Context and description

Player 1's name is assigned fine, and then it prompts for player 2's name. after submitting that, it deletes player 2's name, and then assigns the input to player...1. In order to get this to replace only one name, at I time, I am nesting click functions. console.log shows that the issue is that I am caling both click functions on the second click (i.e. I replace name 1, click for name 2, replace name 2 and then replace name 1 with what was put into name two. At least that's the order I'm seeing).
## 

Error:
no error message, just the problem above

**Comment by emilylordahl** [comment]
Resolved!
